version: '3.4'

services:
  contosouniversity:
    image: ${DOCKER_REGISTRY-}contosouniversity
    build:
      context: .
      dockerfile: ContosoUniversity/Dockerfile
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"